### ISSUE TITLE
QBFT Consensus client

### ISSUE THREAD

**Issue by Filter94** [Consensys/maru#1]
## Description
We need to switch Linea from Clique to QBFT in order to leverage Engine API

## Motivation
It would allow Linea to support newer EL forks (Paris and onwards) which most importantly will unlock all the recent EVM features

## Architecture
- [ ] TBA

### Migration
- [ ] Clique to post merge POC

### Main
- [ ] Create CLI for the Consensus client
- [ ] Application configuration
- [ ] Peering with other CL-QBFT nodes
- [ ] Json API to provide beacon chain and validator details (consider compatibility with standard CL API)

### QBFT
- [ ] Integrate QBFT core and state machine in CL so it can produce empty blocks
- [ ] Adapt QBFT to use beacon chain blocks 
- [ ] Use engine API to create EL payload when building Proposal
- [ ] Use engine API to notify and verify EL of a new block when receiving Proposal
- [ ] Use engine API to update EL chain head using FCU when quorum of Commits is received
- [ ] Convert QBFT to get validator set of validators from smart contract read using `eth_call`
- [ ] Implement finalized block height polling logic to set finalized block
- [ ] Implement syncing

### Beacon chain
- [ ] Add logic to store Beacon chain state
- [ ] Add Beacon chain read JsonRPC API, consider compatibility with the existing observability tooling

### Build
- [ ] Implement Docker compose setup
- [ ] Setup CI pipelines to build the client, push docker image and run E2E tests

### Testing
- [ ] Add E2E tests
- [ ] Add chaos tests / Devnet setup
- [ ] Setup network monitoring tooling

## Metrics/monitoring
- [ ] Topology of the network
- [ ] List of participating nodes
- [ ] Beacon chain explorer?
- [ ] Observability spike

## Rollout
- [ ] TBA

## Infrastructure & Node operators
- [ ] TBA

## Documentation & communication
- [ ] TBA
