### ISSUE TITLE
Clique to post merge POC

### ISSUE THREAD

**Issue by Filter94** [Consensys/maru#3]
## Description
We need to make a POC to figure out exactly how switch from Clique to engine API. Since we're missing QBFT CL / EL setup we can test it out on an example of POS

## Motivation
This is needed to see how different nodes behave (Besu and Geth) and how the switch will look like on node runner's side

## Tasks
- [ ] Create a working docker-compose setup with Genesis file starting from Clique and switching to Paris fork, driven by engine API
- [ ] Manual block production after the switch (with curl) is acceptable

## Acceptance criteria
- [ ] We have a defined instruction how to switch a Clique network to Merge API or we learn the limitations of the clients available off the shelf (mainly Geth v 1.14+)

## Risks
- [ ] No risks since this work is expected to be done in docker-compose

## Remember to
 - [ ] Add the `documentation` label in case there is an impact on the documentation
 - [ ] Add `priority` and `team` labels
 - [ ] Add Task for updating the Runbook or adding/updating existing metrics and alerts.
