### ISSUE TITLE
Create CLI for the Consensus client

### ISSUE THREAD

**Issue by Filter94** [Consensys/maru#4]
## Description
We need to create a working entrypoint for the consensus client

## Motivation
Even though the implementation of the consensus client is not ready yet, we can start with the CLI, automate its build and publish process and build on top of it

## Tasks
- [ ] Create a consensus client CLI that doesn't have to do much yet, but should parse the configuration correctly and be extensible

## Acceptance criteria
- [ ] Consensus client is buildable and runnable

## Risks
- [ ] I guess none

## Remember to
 - [ ] Add the `documentation` label in case there is an impact on the documentation
 - [ ] Add `priority` and `team` labels
 - [ ] Add Task for updating the Runbook or adding/updating existing metrics and alerts.
