### ISSUE TITLE
Setup CI pipelines to build the client, push docker image and run E2E tests

### ISSUE THREAD

**Issue by Filter94** [Consensys/maru#5]
## Description
We need to create a CI pipeline to build the contents of the repo, run tests and publish built docker image

## Motivation
Many benefits to that

## Tasks
- [ ] Integrate build process with GHA
- [ ] Ensure tests are running on CI
- [ ] Ensure docker image of the consensus client is built and published
- [ ] Optional: integrate E2E tests. Optional because E2E might not be ready by the time this ticket is worked on

## Acceptance criteria
- [ ] There's a GHA pipeline that is building the consensus client, running the tests and publishing the docker image to docker repo

## Risks
- [ ] CI pipeline has to be built with external contributors in mind. They shouldn't be able to publish docker images into linea public repo
- [ ] External contributors shouldn't be able to spam with E2E test runs as they're relatively expensive on Linea's wallet

## Remember to
 - [ ] Add the `documentation` label in case there is an impact on the documentation
 - [ ] Add `priority` and `team` labels
 - [ ] Add Task for updating the Runbook or adding/updating existing metrics and alerts.
