### ISSUE TITLE
Add logic to store Beacon chain state

### ISSUE THREAD

**Issue by Filter94** [Consensys/maru#6]
## Description
We need to introduce logic to store Beacon chain's state

## Motivation
Beacon chain state is needed for external nodes to sync with the network and know which blocks to import

## Tasks
- [ ] Implement beacon chain state storage data structures
- [ ] Implement API to add new beacon chain blocks to the storage
- [ ] Add persistence, RocksDB based
- [ ] Add API to retreive arbitrary beacon chain blocks
- [ ] Keep testability in mind, it might be good to implement in memory test doubles instead of RocksDB per sistence implementation

## Acceptance criteria
- [ ] Beacon chain is able to accept new blocks
- [ ] Beacon chain is able to retrieve arbitrary blocks
- [ ] Beacon chain is persisted on disk and it's resilient to arbitrary errors and power outages
- [ ] Beacon chain has adequate test coverage

## Risks
- [ ] Persistence is done in corruption-resistant way
- [ ] The implementation is testable

## Remember to
 - [ ] Add the `documentation` label in case there is an impact on the documentation
 - [ ] Add `priority` and `team` labels
 - [ ] Add Task for updating the Runbook or adding/updating existing metrics and alerts.
