### ISSUE TITLE
Observability spike for Beacon chain

### ISSUE THREAD

**Issue by gauravahuja** [Consensys/maru#8]
## Description
Figure out the the subset of UI features that we need to function in something like Beaconscan or [dora](https://github.com/ethpandaops/dora) for the linea beacon chain. 

## Motivation
Helps to easily figure out the state of the chain and debug issues.

## Tasks
- [ ] Shortlist the UI features that we need
- [ ] List the set of Beacon APIs and data structures needed for the UI features
- [ ] Figure out how do we map our Beacon state to the data required for the APIs

## Acceptance criteria
- [ ] 

## Risks
- [ ]

## Remember to
 - [ ] Add the `documentation` label in case there is an impact on the documentation
 - [ ] Add `priority` and `team` labels
 - [ ] Add Task for updating the Runbook or adding/updating existing metrics and alerts.
